server:
  port: 9099

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:////Users/junggeunkim/Workspace/kjg.leh/msa-config-repository

